import type {
  GitHubAccount,
  GitHubRepository,
  UiPlugin,
  UiRepository,
  UiSkill,
  UiTask,
} from "./api";

export const initialRepos: UiRepository[] = [
  {
    id: "content",
    name: "example-org/content-skill-kit",
    type: "skill repo",
    ref: "main",
    skills: 3,
    remoteSha: "a1b2c3d",
    lastBackupSha: "7f8e9ab",
    lastChecked: "Jun 14 09:32",
    backupStatus: "updated-not-backed-up",
    checkStatus: "success",
    url: "https://github.com/example-org/content-skill-kit",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/content-skill-kit",
    snapshotTime: "2026-06-12 18:03",
    recognizedSkills: [
      { name: "content-skill-core", version: "v1.2.0" },
      { name: "content-skill-plugins", version: "v1.1.1" },
      { name: "content-skill-utils", version: "v0.9.3" },
    ],
    recognizedPlugins: [
      {
        id: "plugin-content-marketplace",
        name: "content-skill-kit",
        kind: "codex-marketplace",
        installCommand: "/plugin install content-skill-kit@content-skill-kit",
        skillCount: 1,
      },
      {
        id: "plugin-content-clawhub",
        name: "content-skill-core",
        kind: "clawhub-skill",
        installCommand: "clawhub install content-skill-core",
        skillCount: 1,
      },
    ],
  },
  {
    id: "cookbook",
    name: "example-org/reference-cookbook",
    type: "generic repo",
    ref: "main",
    skills: 0,
    remoteSha: "e4f5g6h",
    lastBackupSha: "e4f5g6h",
    lastChecked: "Jun 14 09:31",
    backupStatus: "backed-up-latest",
    checkStatus: "success",
    url: "https://github.com/example-org/reference-cookbook",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/reference-cookbook",
    snapshotTime: "2026-06-14 09:05",
    recognizedSkills: [],
  },
  {
    id: "missing",
    name: "example-org/missing-skill",
    type: "unknown",
    ref: "main",
    skills: 0,
    remoteSha: "unknown",
    lastBackupSha: "none",
    lastChecked: "Jun 14 09:30",
    backupStatus: "check-failed",
    checkStatus: "failed",
    url: "https://github.com/example-org/missing-skill",
    branch: "main",
    backupPath: "Unavailable",
    snapshotTime: "Never",
    recognizedSkills: [],
  },
  {
    id: "langchain",
    name: "example-org/agent-framework",
    type: "skill repo",
    ref: "main",
    skills: 5,
    remoteSha: "5aa7bb1",
    lastBackupSha: "1122abc",
    lastChecked: "Jun 14 09:28",
    backupStatus: "updated-not-backed-up",
    checkStatus: "success",
    url: "https://github.com/example-org/agent-framework",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/agent-framework",
    snapshotTime: "2026-06-10 12:22",
    recognizedSkills: [
      { name: "prompt-tooling", version: "v0.8.2" },
      { name: "agent-recipes", version: "v0.4.0" },
    ],
  },
  {
    id: "vscode",
    name: "example-org/editor-core",
    type: "generic repo",
    ref: "main",
    skills: 0,
    remoteSha: "0f1e2d3",
    lastBackupSha: "0f1e2d3",
    lastChecked: "Jun 14 09:27",
    backupStatus: "backed-up-latest",
    checkStatus: "success",
    url: "https://github.com/example-org/editor-core",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/editor-core",
    snapshotTime: "2026-06-14 08:11",
    recognizedSkills: [],
  },
  {
    id: "spec",
    name: "example-org/spec-writer-skill",
    type: "skill repo",
    ref: "main",
    skills: 1,
    remoteSha: "08ff12a",
    lastBackupSha: "none",
    lastChecked: "Jun 14 09:24",
    backupStatus: "never-backed-up",
    checkStatus: "success",
    url: "https://github.com/example-org/spec-writer-skill",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/spec-writer-skill",
    snapshotTime: "Never",
    recognizedSkills: [{ name: "spec-writer-skill", version: "v0.2.1" }],
  },
  {
    id: "linux",
    name: "example-org/kernel-mirror",
    type: "generic repo",
    ref: "master",
    skills: 0,
    remoteSha: "9abc8de",
    lastBackupSha: "9abc8de",
    lastChecked: "Jun 14 09:21",
    backupStatus: "backed-up-latest",
    checkStatus: "success",
    url: "https://github.com/example-org/kernel-mirror",
    branch: "master",
    backupPath: "~/SkillRepoBackups/example-org/kernel-mirror",
    snapshotTime: "2026-06-14 07:30",
    recognizedSkills: [],
  },
  {
    id: "anthropic",
    name: "example-org/research-cookbook",
    type: "generic repo",
    ref: "main",
    skills: 0,
    remoteSha: "c0ffee1",
    lastBackupSha: "c0ffee1",
    lastChecked: "Jun 14 09:20",
    backupStatus: "backed-up-latest",
    checkStatus: "success",
    url: "https://github.com/example-org/research-cookbook",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/research-cookbook",
    snapshotTime: "2026-06-13 16:44",
    recognizedSkills: [],
  },
  {
    id: "flask",
    name: "example-org/web-framework-skill",
    type: "skill repo",
    ref: "main",
    skills: 1,
    remoteSha: "12ab34c",
    lastBackupSha: "0a9b111",
    lastChecked: "Jun 14 09:19",
    backupStatus: "updated-not-backed-up",
    checkStatus: "success",
    url: "https://github.com/example-org/web-framework-skill",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/web-framework-skill",
    snapshotTime: "2026-06-09 12:30",
    recognizedSkills: [{ name: "flask-helper", version: "v0.3.1" }],
  },
  {
    id: "fastapi",
    name: "example-org/api-framework-skills",
    type: "skill repo",
    ref: "main",
    skills: 2,
    remoteSha: "89de012",
    lastBackupSha: "89de012",
    lastChecked: "Jun 14 09:18",
    backupStatus: "backed-up-latest",
    checkStatus: "success",
    url: "https://github.com/example-org/api-framework-skills",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/api-framework-skills",
    snapshotTime: "2026-06-14 06:18",
    recognizedSkills: [
      { name: "api-docs-skill", version: "v1.0.0" },
      { name: "routing-helper", version: "v0.4.5" },
    ],
  },
  {
    id: "requests",
    name: "example-org/http-client",
    type: "generic repo",
    ref: "main",
    skills: 0,
    remoteSha: "345f678",
    lastBackupSha: "345f678",
    lastChecked: "Jun 14 09:17",
    backupStatus: "backed-up-latest",
    checkStatus: "success",
    url: "https://github.com/example-org/http-client",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/http-client",
    snapshotTime: "2026-06-13 19:10",
    recognizedSkills: [],
  },
  {
    id: "django",
    name: "example-org/cache-maintenance-skill",
    type: "skill repo",
    ref: "main",
    skills: 1,
    remoteSha: "6b7c8d9",
    lastBackupSha: "2255aee",
    lastChecked: "Jun 14 09:16",
    backupStatus: "updated-not-backed-up",
    checkStatus: "success",
    url: "https://github.com/example-org/cache-maintenance-skill",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/cache-maintenance-skill",
    snapshotTime: "2026-06-11 10:42",
    recognizedSkills: [{ name: "redis-maintenance", version: "v0.1.8" }],
  },
  {
    id: "postgresql",
    name: "example-org/api-stack-skills",
    type: "skill repo",
    ref: "main",
    skills: 4,
    remoteSha: "abcd123",
    lastBackupSha: "abcd123",
    lastChecked: "Jun 14 09:15",
    backupStatus: "backed-up-latest",
    checkStatus: "success",
    url: "https://github.com/example-org/api-stack-skills",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/api-stack-skills",
    snapshotTime: "2026-06-14 03:11",
    recognizedSkills: [{ name: "postgres-stack", version: "v0.7.2" }],
  },
  {
    id: "hello",
    name: "example-org/hello-world",
    type: "generic repo",
    ref: "master",
    skills: 0,
    remoteSha: "1a2b3c4",
    lastBackupSha: "1a2b3c4",
    lastChecked: "Jun 14 09:14",
    backupStatus: "backed-up-latest",
    checkStatus: "success",
    url: "https://github.com/example-org/hello-world",
    branch: "master",
    backupPath: "~/SkillRepoBackups/example-org/hello-world",
    snapshotTime: "2026-06-10 21:00",
    recognizedSkills: [],
  },
  {
    id: "awesome",
    name: "example-org/curated-list",
    type: "generic repo",
    ref: "main",
    skills: 0,
    remoteSha: "7f8e9ab",
    lastBackupSha: "7f8e9ab",
    lastChecked: "Jun 14 09:13",
    backupStatus: "backed-up-latest",
    checkStatus: "success",
    url: "https://github.com/example-org/curated-list",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/curated-list",
    snapshotTime: "2026-06-13 14:02",
    recognizedSkills: [],
  },
  {
    id: "local-example",
    name: "example-org/local-skill-playground",
    type: "skill repo",
    ref: "main",
    skills: 2,
    remoteSha: "deaf999",
    lastBackupSha: "001abba",
    lastChecked: "Jun 14 09:12",
    backupStatus: "updated-not-backed-up",
    checkStatus: "success",
    url: "https://github.com/example-org/local-skill-playground",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/local-skill-playground",
    snapshotTime: "2026-06-07 11:58",
    recognizedSkills: [{ name: "example-skill", version: "v0.1.0" }],
  },
  {
    id: "archived-example",
    name: "example-org/archived-skill-repo",
    type: "unknown",
    ref: "main",
    skills: 0,
    remoteSha: "unknown",
    lastBackupSha: "none",
    lastChecked: "Jun 14 09:11",
    backupStatus: "check-failed",
    checkStatus: "failed",
    url: "https://github.com/example-org/archived-skill-repo",
    branch: "main",
    backupPath: "Unavailable",
    snapshotTime: "Never",
    recognizedSkills: [],
  },
  {
    id: "ml-notes",
    name: "example-org/ml-notes-skill",
    type: "skill repo",
    ref: "main",
    skills: 3,
    remoteSha: "b16b00b",
    lastBackupSha: "b16b00b",
    lastChecked: "Jun 14 09:10",
    backupStatus: "backed-up-latest",
    checkStatus: "success",
    url: "https://github.com/example-org/ml-notes-skill",
    branch: "main",
    backupPath: "~/SkillRepoBackups/example-org/ml-notes-skill",
    snapshotTime: "2026-06-14 05:46",
    recognizedSkills: [{ name: "ml-notes-reader", version: "v2.0.0" }],
  },
].map((repository) => ({ ...repository, sourceType: "github" }));

export const initialSkills: UiSkill[] = [
  {
    id: "prd",
    repoId: "spec",
    name: "spec-writer-skill",
    description: "Generate AI-implementable product specification documents.",
    repo: "example-org/spec-writer-skill",
    path: "skills/spec-writer-skill",
    ref: "main",
    localVersion: "08aa901",
    remoteVersion: "08ff12a",
    status: "update-conflict",
    installed: true,
    installPath: "~/SkillRepoTracker/skills/spec-writer-skill",
    updatedAt: "2026-06-10 18:20",
  },
  {
    id: "source",
    repoId: "source",
    name: "source-reviewer-skill",
    description: "Review source credibility and evidence quality.",
    repo: "example-org/source-reviewer-skill",
    path: ".",
    ref: "main",
    localVersion: "61cc2bd",
    remoteVersion: "61cc2bd",
    status: "installed-latest",
    installed: true,
    updatedAt: "2026-06-14 08:21",
  },
  {
    id: "content-core",
    repoId: "content",
    name: "content-skill-core",
    description: "Core content studio workflow Skill.",
    repo: "example-org/content-skill-kit",
    path: "skills/content-skill-core",
    ref: "main",
    localVersion: "7f8e9ab",
    remoteVersion: "a1b2c3d",
    status: "update-available",
    installed: true,
    updatedAt: "2026-06-12 09:00",
    plugins: [
      {
        id: "plugin-content-marketplace",
        name: "content-skill-kit",
        kind: "codex-marketplace",
        installCommand: "/plugin install content-skill-kit@content-skill-kit",
      },
      {
        id: "plugin-content-clawhub",
        name: "content-skill-core",
        kind: "clawhub-skill",
        installCommand: "clawhub install content-skill-core",
      },
    ],
  },
  {
    id: "scene",
    repoId: "scene",
    name: "scene-director-skill",
    description: "Stage scene design prompts and direction notes.",
    repo: "example-org/scene-director-skill",
    path: ".",
    ref: "main",
    localVersion: "not installed",
    remoteVersion: "e4f9912",
    status: "not-installed",
    installed: false,
    updatedAt: "Never",
  },
  {
    id: "broken",
    repoId: "missing",
    name: "missing-skill",
    description: "Source repository cannot be reached.",
    repo: "example-org/missing-skill",
    path: "skills/missing",
    ref: "main",
    localVersion: "2bba019",
    remoteVersion: "unknown",
    status: "source-unavailable",
    installed: true,
    updatedAt: "2026-06-01 11:34",
  },
];

export const initialPlugins: UiPlugin[] = [
  {
    id: "plugin-content-marketplace",
    repoId: "content",
    repoName: "example-org/content-skill-kit",
    name: "content-skill-kit",
    description: "Codex plugin marketplace entry for the content skill kit.",
    kind: "codex-marketplace",
    installCommand: "/plugin install content-skill-kit@content-skill-kit",
    updateCommand: null,
    sourcePath: "README.md",
    sourceExcerpt: "/plugin marketplace add example-org/content-skill-kit\n/plugin install content-skill-kit@content-skill-kit",
    status: "detected",
    skillCount: 1,
    detectedSha: "a1b2c3d",
    createdAt: "2026-06-14 10:18",
    updatedAt: "2026-06-14 10:18",
    note: "",
    linkedSkills: [
      {
        id: "content-core",
        name: "content-skill-core",
        path: "skills/content-skill-core",
        version: "a1b2c3d",
        status: "update-available",
      },
    ],
  },
  {
    id: "plugin-content-clawhub",
    repoId: "content",
    repoName: "example-org/content-skill-kit",
    name: "content-skill-core",
    description: "ClawHub single-Skill install entry.",
    kind: "clawhub-skill",
    installCommand: "clawhub install content-skill-core",
    updateCommand: null,
    sourcePath: "README.md",
    sourceExcerpt: "clawhub install content-skill-core",
    status: "detected",
    skillCount: 1,
    detectedSha: "a1b2c3d",
    createdAt: "2026-06-14 10:18",
    updatedAt: "2026-06-14 10:18",
    note: "",
    linkedSkills: [
      {
        id: "content-core",
        name: "content-skill-core",
        path: "skills/content-skill-core",
        version: "a1b2c3d",
        status: "update-available",
      },
    ],
  },
];

export const initialTasks: UiTask[] = [
  {
    id: "backup-213012",
    kind: "Backup repositories",
    target: "Updated repositories",
    progress: "7 / 12",
    status: "partial-success",
    summary: "7 success, 1 failed, 4 queued",
    retryable: false,
    log: [
      "refresh remote state for 17 repositories",
      "skip example-org/missing-skill because check failed",
      "download example-org__content-skill-kit__main__a1b2c3d.zip",
      "compute sha256: 19a6...4de1",
      "write manifest.json",
      "update last_backup_sha for successful items",
    ],
  },
  {
    id: "check-0932",
    kind: "Check remote state",
    target: "All repositories",
    progress: "17 / 17",
    status: "success",
    summary: "15 success, 2 failed",
    retryable: false,
    log: [
      "resolve default refs",
      "record remote_head_sha for public repositories",
      "keep previous SHA for failed repositories",
    ],
  },
  {
    id: "skill-0831",
    kind: "Update Skill",
    target: "spec-writer-skill",
    progress: "0 / 1",
    status: "waiting-user",
    summary: "waiting for user to update local Skill",
    retryable: false,
    log: [
      "calculate installed_skill_hash",
      "local content differs from installation record",
      "waiting for user-managed update with Agent tools",
    ],
  },
  {
    id: "interrupted",
    kind: "Backup repositories",
    target: "Previous session",
    progress: "4 / 9",
    status: "interrupted",
    summary: "app closed during ZIP download",
    retryable: false,
    log: ["task interrupted before manifest write", "last_backup_sha not updated"],
  },
];

export const initialGithubAccounts: GitHubAccount[] = [
  {
    id: "github:demo",
    login: "demo-user",
    displayName: "Demo user",
    avatarUrl: null,
    status: "verified",
    scopes: "repo, user, starring",
    lastVerified: "2026-06-30 10:00",
  },
];

export const initialGithubRepositories: GitHubRepository[] = [
  {
    accountId: "github:demo",
    accountLogin: "demo-user",
    owner: "example-org",
    repo: "private-skill-kit",
    fullName: "example-org/private-skill-kit",
    htmlUrl: "https://github.com/example-org/private-skill-kit",
    description: "Private Skill source repository with installable workflows.",
    visibility: "private",
    private: true,
    fork: false,
    archived: false,
    defaultBranch: "main",
    language: "TypeScript",
    stargazersCount: 12,
    starred: true,
    trackedRepoId: null,
    pushedAt: "2026-06-29 18:00",
    updatedAt: "2026-06-29 18:00",
    lastRefreshed: "2026-06-30 10:00",
    permissions: "pull, push",
    note: "",
  },
  {
    accountId: "github:demo",
    accountLogin: "demo-user",
    owner: "example-org",
    repo: "reference-cookbook",
    fullName: "example-org/reference-cookbook",
    htmlUrl: "https://github.com/example-org/reference-cookbook",
    description: "Fictional examples and guides for local demo workflows.",
    visibility: "public",
    private: false,
    fork: false,
    archived: false,
    defaultBranch: "main",
    language: "MDX",
    stargazersCount: 72000,
    starred: true,
    trackedRepoId: "cookbook",
    pushedAt: "2026-06-28 11:00",
    updatedAt: "2026-06-28 11:00",
    lastRefreshed: "2026-06-30 10:00",
    permissions: "pull",
    note: "",
  },
];
